base_url = "https://feliciterra.com"
title = "Feliciterra"
description = "feliciterra.com"
compile_sass = false
minify_html = false
generate_feeds = false

[extra]
assets_base_url = "https://assets.feliciterra.com"
