base_url = "https://www.feliciterra.com"
title = "Feliciterra"
description = "The Turney Family Network"
compile_sass = false
minify_html = false
generate_feeds = false

[extra]
assets_base_url = "https://assets.feliciterra.com"
monogram_url = "https://assets.feliciterra.com/monogram.jpg"
